= README =
:toc:       
:toc-title: Table of Contents
:sectnums:
:experimental:
:icons:     font

== Introduction ==
Quick introduction to the project. Explain what it is, the functionality, and common usage.

== Status ==
Current status of project. Optionally include link to changelog

== License ==
THIS SOFTWARE COMES WITHOUT WARRANTY, LIABILITY, OR SUPPORT!

== Requirements ==
Required items for the project (building, running, etc)

== Installation ==
Procedure to install project

== Usage ==
Quick explanation of project usage, examples if library and quick tips if application

== Documentation ==
Additional project documentation

== Standards ==
List any standards (naming, versioning, etc) used by the project.

== Issues ==
List of known issues/bugs

== Roadmap ==
Plan of upcoming changes/features

== Contacts ==
Information for contacting project maintainers

== Contributing ==
Information for contributing to the project

== Similar ==
Reference information about similar projects

== FAQ ==
Answers to questions not covered in other sections
